### ISSUE TITLE
Copyright violation.

### ISSUE THREAD

**Issue by korbosoft** [hackmiiusr999/Hanobi-Wii-Project0#2]
it is **HIGHLY ILLEGAL** to post csm files online, as they are modified versions of Nintendo-made files.

**Comment by hackmiiusr999** [comment]
So could I try to create an entirely different theme with no similarities or should I just change the theme format entirely. This was a bit of an abandoned project.

**Comment by korbosoft** [comment]
> So could I try to create an entirely different theme with no similarities or should I just change the theme format entirely. This was a bit of an abandoned project.

rather than ppsting the csm, post the mym.
